name: FRACTAL-PROMPT Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-fractal-prompt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Download FRACTAL-PROMPT CLI
      run: |
        curl -L -o fractal-cli.py https://raw.githubusercontent.com/juampiat/fractal-prompt/main/TOOLS/fractal-cli.py
        chmod +x fractal-cli.py

    - name: Validate FRACTAL-PROMPT compliance
      run: |
        python3 fractal-cli.py status

    - name: Check for required templates
      run: |
        # Check if project has FRACTAL-PROMPT templates
        if [ ! -f "PROJECT_INITIATION.md" ] && [ ! -f "fractal-config.json" ]; then
          echo "⚠️  No FRACTAL-PROMPT templates found in project root"
          echo "💡 Consider running: fractal-cli init <project-name>"
          exit 1
        fi

    - name: Validate project structure
      run: |
        # Check for basic project documentation
        if [ ! -f "README.md" ]; then
          echo "❌ README.md is required for FRACTAL-PROMPT compliance"
          exit 1
        fi

        # Check for backup protocols
        if ! grep -q "backup\|Backup" README.md; then
          echo "⚠️  Consider documenting backup protocols in README.md"
        fi

    - name: Run collaboration checkpoint
      run: |
        # Create or validate collaboration checkpoint
        if [ ! -f "COLLABORATION_CHECKPOINT.md" ]; then
          echo "📋 Creating collaboration checkpoint template"
          curl -s https://raw.githubusercontent.com/juampiat/fractal-prompt/main/TEMPLATES/COLLABORATION_CHECKPOINT.md > COLLABORATION_CHECKPOINT.md
        fi

    - name: Generate compliance report
      run: |
        echo "# FRACTAL-PROMPT Compliance Report" > fractal-compliance.md
        echo "" >> fractal-compliance.md
        echo "## Validation Results" >> fractal-compliance.md
        echo "- ✅ Repository structure validated" >> fractal-compliance.md
        echo "- ✅ FRACTAL-PROMPT templates present" >> fractal-compliance.md
        echo "- ✅ Collaboration protocols documented" >> fractal-compliance.md
        echo "" >> fractal-compliance.md
        echo "## Next Steps" >> fractal-compliance.md
        echo "1. Review project documentation" >> fractal-compliance.md
        echo "2. Update collaboration checkpoints" >> fractal-compliance.md
        echo "3. Share learnings with the community" >> fractal-compliance.md
        echo "" >> fractal-compliance.md
        echo "*Generated by FRACTAL-PROMPT GitHub Action*" >> fractal-compliance.md

    - name: Upload compliance report
      uses: actions/upload-artifact@v3
      with:
        name: fractal-compliance-report
        path: fractal-compliance.md

    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('fractal-compliance.md', 'utf8');

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🤝 FRACTAL-PROMPT Compliance Report

${report}

*This comment was automatically generated by the FRACTAL-PROMPT GitHub Action.*`
          });